-- =============================================================
-- EKSPORT SCHEMATU PROD → DEV (NIE ZMIENIA BAZY, BEZ DANYCH OSOBOWYCH)
-- 1. Uruchom na PRODUKCJI (SQL Editor) — całość naraz; wynik to jedna komórka "ddl".
-- 2. Skopiuj ją w całości do pliku supabase/dev/schema-from-prod.sql.
-- 3. Uruchom ten plik w SQL Editor projektu LSO-dev.
-- Tworzy tylko funkcję tymczasową (pg_temp), która znika po zakończeniu sesji.
-- Każda sekcja liczy się osobno: jeśli któraś się nie uda, w wyniku pojawi się
-- linia "-- !!! BŁĄD w sekcji ...", a reszta i tak się wygeneruje.
-- Kopiuje: rozszerzenia, typy, tabele, widoki, funkcje, wartości domyślne, klucze,
-- indeksy, triggery, RLS i polityki, realtime, buckety storage oraz systemowe
-- rangi i odznaki (parish_id = NULL).
-- NIE kopiuje: użytkowników, parafii, żadnych danych osób, zadań pg_cron.
-- =============================================================
create or replace function pg_temp.lso_export_schema()
returns text language plpgsql as $f$
declare
  result text := '-- Schemat wygenerowany z produkcji LSO ' || now()::date || ' — uruchom w projekcie LSO-dev'
                 || E'\n\nset check_function_bodies = off;';
  part text;
begin
  -- rozszerzenia
  begin
    select string_agg(format(
      'do $x$ begin create extension if not exists %I with schema %I; exception when others then raise notice %L; end $x$;',
      e.extname, n.nspname, 'pominięto rozszerzenie ' || e.extname), E'\n' order by e.extname)
      into part
      from pg_extension e join pg_namespace n on n.oid = e.extnamespace
     where e.extname <> 'plpgsql';
    result := result || E'\n\n-- rozszerzenia\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji rozszerzenia: ' || sqlerrm;
  end;

  -- typy (enum)
  begin
    select string_agg(format('create type public.%I as enum (%s);', t.typname,
      (select string_agg(quote_literal(en.enumlabel), ', ' order by en.enumsortorder) from pg_enum en where en.enumtypid = t.oid)),
      E'\n' order by t.typname)
      into part
      from pg_type t join pg_namespace n on n.oid = t.typnamespace
     where n.nspname = 'public' and t.typtype = 'e';
    result := result || E'\n\n-- typy\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji typy: ' || sqlerrm;
  end;

  -- sekwencje (bez tych od kolumn identity)
  begin
    select string_agg(format('create sequence if not exists public.%I;', c.relname), E'\n' order by c.relname)
      into part
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind = 'S'
       and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'i');
    result := result || E'\n\n-- sekwencje\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji sekwencje: ' || sqlerrm;
  end;

  -- tabele (bez wartości domyślnych i kluczy — dochodzą niżej)
  begin
    select string_agg(format('create table public.%I (%s);', c.relname,
      (select string_agg(format('%I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
          case a.attidentity when 'a' then ' generated always as identity'
                             when 'd' then ' generated by default as identity' else '' end
          || case when a.attgenerated = 's'
                  then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored' else '' end,
          case when a.attnotnull then ' not null' else '' end), ', ' order by a.attnum)
         from pg_attribute a
         left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
        where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)),
      E'\n' order by c.relname)
      into part
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind in ('r', 'p');
    result := result || E'\n\n-- tabele\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji tabele: ' || sqlerrm;
  end;

  -- widoki
  begin
    select string_agg(format('create or replace view public.%I%s as %s',
      c.relname,
      case when c.reloptions is not null then ' with (' || array_to_string(c.reloptions, ', ') || ')' else '' end,
      pg_get_viewdef(c.oid)), E'\n\n' order by c.oid)
      into part
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind = 'v';
    result := result || E'\n\n-- widoki\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji widoki: ' || sqlerrm;
  end;

  -- funkcje
  begin
    select string_agg(pg_get_functiondef(p.oid) || ';', E'\n\n' order by p.proname)
      into part
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.prokind = 'f'
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e');
    result := result || E'\n\n-- funkcje\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji funkcje: ' || sqlerrm;
  end;

  -- wartości domyślne
  begin
    select string_agg(format('alter table public.%I alter column %I set default %s;',
      c.relname, a.attname, pg_get_expr(ad.adbin, ad.adrelid)), E'\n' order by c.relname, a.attnum)
      into part
      from pg_attrdef ad
      join pg_class c on c.oid = ad.adrelid
      join pg_namespace n on n.oid = c.relnamespace
      join pg_attribute a on a.attrelid = ad.adrelid and a.attnum = ad.adnum
     where n.nspname = 'public' and a.attgenerated = '';
    result := result || E'\n\n-- wartości domyślne\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji wartości domyślne: ' || sqlerrm;
  end;

  -- klucze i ograniczenia (obce na końcu)
  begin
    select string_agg(format('alter table public.%I add constraint %I %s;',
      c.relname, con.conname, pg_get_constraintdef(con.oid)),
      E'\n' order by (con.contype = 'f'), c.relname, con.conname)
      into part
      from pg_constraint con
      join pg_class c on c.oid = con.conrelid
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and con.contype in ('p', 'u', 'c', 'x', 'f');
    result := result || E'\n\n-- klucze i ograniczenia\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji klucze: ' || sqlerrm;
  end;

  -- indeksy (bez tych, które tworzą klucze)
  begin
    select string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by c.relname)
      into part
      from pg_index i
      join pg_class c on c.oid = i.indrelid
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid);
    result := result || E'\n\n-- indeksy\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji indeksy: ' || sqlerrm;
  end;

  -- triggery (public + triggery na auth.users wołające funkcje z public)
  begin
    select string_agg(pg_get_triggerdef(t.oid) || ';', E'\n' order by c.relname, t.tgname)
      into part
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      join pg_proc p on p.oid = t.tgfoid
      join pg_namespace pn on pn.oid = p.pronamespace
     where not t.tgisinternal
       and (n.nspname = 'public' or (n.nspname = 'auth' and pn.nspname = 'public'));
    result := result || E'\n\n-- triggery\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji triggery: ' || sqlerrm;
  end;

  -- RLS
  begin
    select string_agg(format('alter table public.%I enable row level security;', c.relname), E'\n' order by c.relname)
      into part
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind in ('r', 'p') and c.relrowsecurity;
    result := result || E'\n\n-- RLS\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji RLS: ' || sqlerrm;
  end;

  -- polityki (public + storage)
  begin
    select string_agg(format('create policy %I on %I.%I as %s for %s to %s%s%s;',
      pol.policyname, pol.schemaname, pol.tablename, pol.permissive, pol.cmd, array_to_string(pol.roles, ', '),
      case when pol.qual is not null then ' using (' || pol.qual || ')' else '' end,
      case when pol.with_check is not null then ' with check (' || pol.with_check || ')' else '' end),
      E'\n' order by pol.schemaname, pol.tablename, pol.policyname)
      into part
      from pg_policies pol
     where pol.schemaname in ('public', 'storage');
    result := result || E'\n\n-- polityki\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji polityki: ' || sqlerrm;
  end;

  -- realtime
  begin
    select string_agg(format('alter publication supabase_realtime add table public.%I;', pt.tablename), E'\n' order by pt.tablename)
      into part
      from pg_publication_tables pt
     where pt.pubname = 'supabase_realtime' and pt.schemaname = 'public';
    result := result || E'\n\n-- realtime\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji realtime: ' || sqlerrm;
  end;

  -- dane słownikowe: systemowe rangi
  begin
    execute $q$
      select format('insert into public.ranks select * from json_populate_recordset(null::public.ranks, %L);', json_agg(r))
        from public.ranks r where r.parish_id is null having count(*) > 0
    $q$ into part;
    result := result || E'\n\n-- dane słownikowe: rangi\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji rangi: ' || sqlerrm;
  end;

  -- dane słownikowe: systemowe odznaki
  begin
    execute $q$
      select format('insert into public.badge_definitions select * from json_populate_recordset(null::public.badge_definitions, %L);', json_agg(b))
        from public.badge_definitions b where b.parish_id is null having count(*) > 0
    $q$ into part;
    result := result || E'\n\n-- dane słownikowe: odznaki\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji odznaki: ' || sqlerrm;
  end;

  -- storage: buckety
  begin
    execute $q$
      select string_agg(format(
        'insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values (%L, %L, %L, %s, %L) on conflict (id) do nothing;',
        bk.id, bk.name, bk."public", coalesce(bk.file_size_limit::text, 'null'), bk.allowed_mime_types), E'\n')
        from storage.buckets bk
    $q$ into part;
    result := result || E'\n\n-- storage\n' || coalesce(part, '');
  exception when others then result := result || E'\n\n-- !!! BŁĄD w sekcji storage: ' || sqlerrm;
  end;

  return result;
end;
$f$;

select pg_temp.lso_export_schema() as ddl;
